### ISSUE TITLE
V3 Tracking Issue

### ISSUE THREAD

**Issue by SiriusStarr** [SiriusStarr/elm-spaced-repetition#9]
Tracking issue for (very slowly) making progress on V3:

- [ ] Add LX algorithm
- [ ] Allow for data-structure-agnostic scheduling (i.e. don't demand an array be passed in).
- [ ] #8 
- [ ] Make a higher-level API that handles multiple decks, switching between them/combining them, etc.
